
class Locale:
    def __init__(self, language):
        if language == "en":
            self.test = "TEST | English"
            self.select_time_zone = "Select time zone"
            self.region = "Region"
            self.timezone = "Zone"
            self.next = "Next"
            self.select_install_option = "Select installation option"
            self.choose_de = "Choose desktop environment"
            self.console = "Console"
            self.diskpart = "Disk Partitioning"
            self.erase_all_and_install = "Erase all drive and install OS"
            self.manual = "Manual"
            self.selfpart = "Self-partitioning of the disk"
            self.rungparted = "Run GParted"
            self.refreshparts = "Refresh disk list"
            self.efipart = "EFI partition (loader)"
            self.rootfs = "Root partition (system and data)"
            self.useswap = "Use swap partition"
            self.swapsize = "Enter the size of the swap partition (GiB)"
            self.securetype = "Use of all security mechanisms"
            self.lessecuretype = "Using backward compatible security mechanisms (less secure)"
            self.insecuretype = "Without using security mechanisms (least secure)"
            self.os_encryption = "OS Encryption"
            self.enckey = "Enter encryption passphrase (US keymap)"
            self.enckey2 = "Enter encrpytion passphrase (repeat)"
        elif language == "ru":
            self.test = "ТЕСТ | Русский"
            self.select_time_zone = "Выберите часовой пояс"
            self.region = "Регион"
            self.timezone = "Пояс"
            self.next = "Далее"
            self.select_install_option = "Выберите вариант установки"
            self.choose_de = "Выберите окружение рабочего стола"
            self.console = "Консольный"
            self.diskpart = "Разметка диска"
            self.erase_all_and_install = "Стереть весь диск и установить ОС"
            self.manual = "Вручную"
            self.selfpart = "Самостоятельная разметка диска"
            self.rungparted = "Запустить GParted"
            self.refreshparts = "Обновить список дисков"
            self.efipart = "EFI раздел (загрузочный)"
            self.rootfs = "Корневой раздел (система и данные)"
            self.useswap = "Использовать раздел подкачки"
            self.swapsize = "Введите размер раздела подкачки (ГиБ)"
            self.securetype = "Использование всех механизмов безопасности"
            self.lessecuretype = "Использование механизмов безопасности с обратной совместимостью (менее безопасно)"
            self.insecuretype = "Без использования механизмов безопасности (наименее безопасно)"
            self.os_encryption = "Шифрование системы"
            self.enckey = "Введите парольную фразу для шифрования (ракладка: США)"
            self.enckey2 = "Введите парольную фразу для шифрования (повтор)"